Add profiling (broken) and PIC flags.
Profiling fails at link time. I think we might need to link against
RTS but I had no such luck. I tried to figure out how to do profiling
build in Buck to see what they do but I failed to find a way. I hacked
Buck to have profiling enabled out of the box and it turns out they
have exactly the same problem.

```
ERROR: /home/shana/.cache/bazel/_bazel_shana/5c33788dab2bc46ef34646c3807ca729/external/examples/hello-world/BUILD:8:1: Linking hello-world failed (Exit 1).
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o(.data+0x108): error: undefined reference to 'CCS_DONT_CARE'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o(.data+0x128): error: undefined reference to 'CCS_DONT_CARE'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o(.data+0x148): error: undefined reference to 'CCS_DONT_CARE'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o:ghc_3.c:function prof_init_Main: error: undefined reference to 'CCS_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o:ghc_3.c:function prof_init_Main: error: undefined reference to 'CCS_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o:ghc_3.c:function prof_init_Main: error: undefined reference to 'CC_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-world/objects/Main.p_o:ghc_3.c:function prof_init_Main: error: undefined reference to 'CC_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-lib/lib/libhello-lib.a(Lib.p_o)(.data+0x108): error: undefined reference to 'CCS_DONT_CARE'
bazel-out/local-fastbuild/bin/external/examples/hello-lib/lib/libhello-lib.a(Lib.p_o):ghc_12.c:function prof_init_hellozmlibzm1zi0zi0_Lib: error: undefined reference to 'CCS_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-lib/lib/libhello-lib.a(Lib.p_o):ghc_12.c:function prof_init_hellozmlibzm1zi0zi0_Lib: error: undefined reference to 'CCS_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-lib/lib/libhello-lib.a(Lib.p_o):ghc_12.c:function prof_init_hellozmlibzm1zi0zi0_Lib: error: undefined reference to 'CC_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-lib/lib/libhello-lib.a(Lib.p_o):ghc_12.c:function prof_init_hellozmlibzm1zi0zi0_Lib: error: undefined reference to 'CC_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-sublib/lib/libhello-sublib.a(MessageSuffix.p_o):ghc_3.c:function prof_init_hellozmsublibzm1zi0zi0_MessageSuffix: error: undefined reference to 'CCS_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-sublib/lib/libhello-sublib.a(MessageSuffix.p_o):ghc_3.c:function prof_init_hellozmsublibzm1zi0zi0_MessageSuffix: error: undefined reference to 'CCS_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-sublib/lib/libhello-sublib.a(MessageSuffix.p_o):ghc_3.c:function prof_init_hellozmsublibzm1zi0zi0_MessageSuffix: error: undefined reference to 'CC_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-sublib/lib/libhello-sublib.a(MessageSuffix.p_o):ghc_3.c:function prof_init_hellozmsublibzm1zi0zi0_MessageSuffix: error: undefined reference to 'CC_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-subsublib/lib/libhello-subsublib.a(MessageEnd.p_o):ghc_3.c:function prof_init_hellozmsubsublibzm1zi0zi0_MessageEnd: error: undefined reference to 'CCS_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-subsublib/lib/libhello-subsublib.a(MessageEnd.p_o):ghc_3.c:function prof_init_hellozmsubsublibzm1zi0zi0_MessageEnd: error: undefined reference to 'CCS_ID'
bazel-out/local-fastbuild/bin/external/examples/hello-subsublib/lib/libhello-subsublib.a(MessageEnd.p_o):ghc_3.c:function prof_init_hellozmsubsublibzm1zi0zi0_MessageEnd: error: undefined reference to 'CC_LIST'
bazel-out/local-fastbuild/bin/external/examples/hello-subsublib/lib/libhello-subsublib.a(MessageEnd.p_o):ghc_3.c:function prof_init_hellozmsubsublibzm1zi0zi0_MessageEnd: error: undefined reference to 'CC_ID'
collect2: error: ld returned 1 exit status
```