Regression test for includes forwarding
Compilation fails with the following error due to not found header
files.

```
tests/library-with-stripped-includes/Lib.hs:5:2: error:
     fatal error: a.h: No such file or directory
     #include "b.h"
      ^~~~~
  |
5 | #include "b.h"
  |  ^
compilation terminated.
`cc' failed in phase `C pre-processor'. (Exit code: 1)
Target //tests/library-with-stripped-includes:library-with-stripped-includes failed to build
```