Use cc_wrapper.runfiles.inputs for REPL
Fixes error due to middleman inputs. See
https://github.com/tweag/rules_haskell/runs/4493235941?check_suite_focus=true#step:7:1798
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//tests/multi_repl:c_only_repl, config=BuildConfigurationValue.Key[0034c9b23a3addb05b6e0c49d378176842931f9429d1501da283d1f28c3c1adf]}, actionIndex=4}' (requested by nodes 'ActionLookupData{actionLookupKey=ConfiguredTargetKey{label=//tests/multi_repl:c_only_repl, config=BuildConfigurationValue.Key[0034c9b23a3addb05b6e0c49d378176842931f9429d1501da283d1f28c3c1adf]}, actionIndex=5}')
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:563)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:398)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: File:[[<execution_root>]bazel-out/host/internal]_middlemen/haskell_Scc_Uwrapper-python-runfiles
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
	at com.google.devtools.build.lib.analysis.Runfiles$ConflictChecker.put(Runfiles.java:651)
	at com.google.devtools.build.lib.analysis.Runfiles.getRunfilesInputs(Runfiles.java:404)
	at com.google.devtools.build.lib.analysis.SourceManifestAction.newDeterministicWriter(SourceManifestAction.java:153)
	at com.google.devtools.build.lib.analysis.actions.AbstractFileWriteAction.beginExecution(AbstractFileWriteAction.java:63)
	at com.google.devtools.build.lib.actions.Action.execute(Action.java:127)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$5.execute(SkyframeActionExecutor.java:855)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.continueAction(SkyframeActionExecutor.java:1016)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor$ActionRunner.run(SkyframeActionExecutor.java:975)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.runStateMachine(ActionExecutionState.java:129)
	at com.google.devtools.build.lib.skyframe.ActionExecutionState.getResultOrDependOnFuture(ActionExecutionState.java:81)
	at com.google.devtools.build.lib.skyframe.SkyframeActionExecutor.executeAction(SkyframeActionExecutor.java:472)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.checkCacheAndExecuteIfNeeded(ActionExecutionFunction.java:834)
	at com.google.devtools.build.lib.skyframe.ActionExecutionFunction.compute(ActionExecutionFunction.java:307)
	at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:477)
	... 4 more
```