Regression test cabal_library collision
Having two haskell_cabal_library targets in the same package fails with
the following collision error.

```
ERROR: file 'tests/haskell_cabal_library/_install/package.conf.d/package.cache' is generated by these conflicting actions:
Label: //tests/haskell_cabal_library:second-lib, //tests/haskell_cabal_library:lib
RuleClass: haskell_cabal_library rule
Configuration: 714c7274e44d92bf3a55b1a39861a10c
Mnemonic: HaskellCabalLibrary
Action key: bfc9b30479665c060e57be9c4d0d48b2, 8aeac69ca2cf5b59f80d79fc0502d926
Progress message: HaskellCabalLibrary //tests/haskell_cabal_library:second-lib, HaskellCabalLibrary //tests/haskell_cabal_library:lib
PrimaryInput: File:[/home/aj/tweag.io/da/bazel-projects/rules_haskell_cabal_outdir[source]]tests/haskell_cabal_library/SecondLib.hs, File:[/home/aj/tweag.io/da/bazel-projects/rules_haskell_cabal_outdir[source]]tests/haskell_cabal_library/Lib.hs
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]tests/haskell_cabal_library/_install/package.conf.d/package.cache
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/haskell_cabal_library/_install/package.conf.d/package.cache, previous action: action 'HaskellCabalLibrary //tests/haskell_cabal_library:lib', attempted action: action 'HaskellCabalLibrary //tests/haskell_cabal_library:second-lib'
```