Join `package_root` paths with path separator
When creating the `package_root` we were appending the paths together
directly. This ended up causing issues when attempting to use `bazel
coverage` in a very specific way.

If a target had a dependency on a package from a different workspace,
when building the target it would fail with a cryptic error like:

```
ERROR: /home/joneshf/.cache/bazel/_bazel_joneshf/82029ba054c9125cad66aaa14166c07e/external/rules_haskell/tools/runfiles/BUILD.bazel:18:1: output 'external/rules_haskell/tools/runfiles/.hpc/externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles/Bazel.Runfiles.mix' was not created
```

The issue was that the directory to find the `mix` files wasn't being
created correctly. There was a path separator missing between the
workspace root and the package:

It would look something like:

```console
$ tail bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/extra_args_runfiles_HaskellBuildLibrary
-ibazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/src
-optP@bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/optp_args_runfiles
-this-unit-id
externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles
-optP-DCURRENT_PACKAGE_KEY="externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles"
external/rules_haskell/tools/runfiles/src/Bazel/Runfiles.hs
-dynamic-too
-fhpc
-hpcdir
bazel-out/k8-fastbuild/bin/external/rules_haskelltools/runfiles/.hpc
```

In particular,
`bazel-out/k8-fastbuild/bin/external/rules_haskelltools/runfiles/.hpc`
is missing a path separator between `rules_haskell` and `tools`.

This change uses `paths.join` instead of string concatenation to create
the `package_root`. The above example now produces something like:

```console
$ tail bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/extra_args_runfiles_HaskellBuildLibrary
-ibazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/src
-optP@bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/optp_args_runfiles
-this-unit-id
externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles
-optP-DCURRENT_PACKAGE_KEY="externalZSrulesZUhaskellZStoolsZSrunfilesZSrunfiles"
external/rules_haskell/tools/runfiles/src/Bazel/Runfiles.hs
-dynamic-too
-fhpc
-hpcdir
bazel-out/k8-fastbuild/bin/external/rules_haskell/tools/runfiles/.hpc
```

Note there is now a path separator between `rules_haskell` and `tools`
in the last line.