Building zlib fails due to -Werror on MacOS
Disables the corresponding warning

```
external/zlib.dev/gzlib.c:252:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
```