Regression test for ghc-check failure
https://github.com/tweag/rules_haskell/pull/1471/checks?check_run_id=1777128453#step:6:170

```
exe/Main.hs:671:24: error:
    • Exception when trying to run compile-time code:
        /home/buildkite-agent-agent/.cache/bazel/_bazel_buildkite-agent-agent/f4185991111fb0b4a69ba9ce941d08aa/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/../lib/settings: openFile: does not exist (No such file or directory)
      Code: makeGhcVersionChecker (pure <$> getLibdir)
    • In the Template Haskell splice
        $$(makeGhcVersionChecker (pure <$> getLibdir))
      In the expression: $$(makeGhcVersionChecker (pure <$> getLibdir))
      In an equation for ‘ghcVersionChecker’:
          ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
    |
671 | ghcVersionChecker = $$(makeGhcVersionChecker (pure <$> getLibdir))
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Traceback (most recent call last):
  File "/home/runner/.cache/bazel/_bazel_runner/c91220d87f26118b19246641d5266d21/sandbox/linux-sandbox/361/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 194, in <module>
    run([runghc] + runghc_args + [setup, "build", "--verbose=0", "--builddir=" + distdir])
  File "/home/runner/.cache/bazel/_bazel_runner/c91220d87f26118b19246641d5266d21/sandbox/linux-sandbox/361/execroot/rules_haskell/bazel-out/host/bin/haskell/cabal_wrapper.runfiles/rules_haskell/haskell/cabal_wrapper.py", line 42, in run
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, *args, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/runner/.cache/bazel/_bazel_runner/c91220d87f26118b19246641d5266d21/sandbox/linux-sandbox/361/execroot/rules_haskell/external/rules_haskell_ghc_linux_amd64/bin/runghc', '/home/runner/.cache/bazel/_bazel_runner/c91220d87f26118b19246641d5266d21/sandbox/linux-sandbox/361/execroot/rules_haskell/bazel-out/k8-fastbuild/bin/external/ghcide/ghcide-0.2.0/Setup.hs', 'build', '--verbose=0', '--builddir=/home/runner/.cache/bazel/_bazel_runner/c91220d87f26118b19246641d5266d21/sandbox/linux-sandbox/361/execroot/rules_haskell/bazel-out/k8-fastbuild/bin/external/ghcide/tmptdqrv7nz']' returned non-zero exit status 1.
```