Add troubleshooting for `cc_toolchain`
Some windows environments have different `cc_toolchain`s installed. If
`bazel` selects the wrong `cc_toolchain`, we'll end up with a
`TypeError` and cryptic error message about a path being None:
```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

To help people find their way, we provide some advice on how to fix
things. The error should be handled properly, but this at least helps
others get unstuck.