Regression test: cabal_library|binary collision
Having a haskell_cabal_library and haskell_cabal_binary in the same
package based on the same Cabal file fails with the following collision
error.

```
ERROR: file 'tests/haskell_cabal_package/_install/package.conf.d/package.cache' is generated by these conflicting actions:
Label: //tests/haskell_cabal_package:lib, //tests/haskell_cabal_package:haskell_cabal_package
RuleClass: haskell_cabal_library rule, haskell_cabal_binary rule
Configuration: 714c7274e44d92bf3a55b1a39861a10c
Mnemonic: HaskellCabalLibrary, HaskellCabalBinary
Action key: 0db4b6214ae988fa02eed064a8920cfb, eced508d50434c291492f51469fc7b5b
Progress message: HaskellCabalLibrary //tests/haskell_cabal_package:lib, HaskellCabalBinary //tests/haskell_cabal_package:haskell_cabal_package
PrimaryInput: File:[/home/aj/tweag.io/da/bazel-projects/rules_haskell_cabal_outdir[source]]tests/haskell_cabal_package/BUILD.bazel
PrimaryOutput: File:[[<execution_root>]bazel-out/k8-fastbuild/bin]tests/haskell_cabal_package/_install/package.conf.d/package.cache
Owner information: //tests/haskell_cabal_package:lib BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false, //tests/haskell_cabal_package:haskell_cabal_package BuildConfigurationValue.Key[714c7274e44d92bf3a55b1a39861a10c] false
MandatoryInputs: Attempted action contains artifacts not in previous action (first 5):
        tests/haskell_cabal_package/cabal_wrapper-lib.sh
Previous action contains artifacts not in attempted action (first 5):
        tests/haskell_cabal_package/_install/package.conf.d/package.cache
        external/rules_haskell_ghc_nixpkgs_haskell_toolchain/lib/ghc-8.6.5/base-4.12.0.0/include/EventConfig.h
        external/rules_haskell_ghc_nixpkgs_haskell_toolchain/lib/ghc-8.6.5/base-4.12.0.0/include/HsBase.h
        external/rules_haskell_ghc_nixpkgs_haskell_toolchain/lib/ghc-8.6.5/base-4.12.0.0/include/HsBaseConfig.h
        external/rules_haskell_ghc_nixpkgs_haskell_toolchain/lib/ghc-8.6.5/base-4.12.0.0/include/WCsubst.h
Outputs: Attempted action contains artifacts not in previous action (first 5):
        tests/haskell_cabal_package/_install/iface
        tests/haskell_cabal_package/_install/lib/libHSlib-0.1.0.0.a
        tests/haskell_cabal_package/_install/lib/libHSlib-0.1.0.0-ghc8.6.5.so
Previous action contains artifacts not in attempted action (first 5):
        tests/haskell_cabal_package/_install/bin/haskell_cabal_package
ERROR: com.google.devtools.build.lib.actions.MutableActionGraph$ActionConflictException: for tests/haskell_cabal_package/_install/package.conf.d/package.cache, previous action: action 'HaskellCabalBinary //tests/haskell_cabal_package:haskell_cabal_package', attempted action: action 'HaskellCabalLibrary //tests/haskell_cabal_package:lib'
```