Skip writing to the remote cache with no API key
For PRs from forks (and also dependabot) access to the repository secrets is not
permitted, so the API key for Buildbuddy ends up as empty.

This would lead to an error:
```
WARNING: BES was not properly closed
ERROR: The Build Event Protocol upload failed: Not retrying publishBuildEvents, no more attempts left: status='Status{code=UNAUTHENTICATED, description=failed to parse AP
```