Update Bazel binary version to 4.2.2
Currently, building on Windows fails with:
```
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.util.concurrent.RejectedExecutionException: Task com.google.common.util.concurrent.TrustedListenableFutureTask@4260669e[status=PENDING, info=[task=[running=[NOT STARTED YET], com.google.devtools.build.lib.remote.ByteStreamBuildEventArtifactUploader$$Lambda$723/0x00000001007b8840@35e164e5]]] rejected from java.util.concurrent.ThreadPoolExecutor@75358050[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2145]
```
That may be a caused by a problem that is already fixed with later versions.